server:
  port: ${LUMALIFE_MERCHANT_PORT:8082}
spring:
  application:
    name: merchant-service
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
info:
  service:
    name: merchant-service
    version: ${SERVICE_VERSION:0.1.0}
    contract-version: v1
