spring:
  autoconfigure:
    exclude: []
  datasource:
    url: jdbc:mysql://${MYSQL_MERCHANT_HOST:${MYSQL_HOST:mysql}}:${MYSQL_MERCHANT_PORT:${MYSQL_PORT:3306}}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER:lifeassist}
    password: ${MYSQL_PASSWORD:}
